# Generated by Django 2.0.8 on 2018-10-10 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=80)),
                ('idade', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino'), ('2', 'Outro')], max_length=1)),
                ('etnia', models.CharField(choices=[('0', 'Albino'), ('1', 'Branco'), ('2', 'Pardo'), ('3', 'Negro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=160)),
                ('commented', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('0', 'Sem prioridade'), ('1', 'Normal'), ('2', 'Urgente'), ('3', 'Muito Urgente'), ('4', 'Ultra Mrga Hiper Urgente')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='coment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_event', to='events.Event'),
        ),
    ]
